apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresclusters/
  - solrclouds/
  - configmaps/
  - jobs/
  - roles/
  - rolebindings/
  - serviceaccounts/
  - services/
  - deployments/
  - issuers/
  - ingresses/
  - rerc/
  - opendatapolicing/
