apiVersion: apps/v1
kind: Deployment
metadata:
  name: rerc
  namespace: scsj-86c3ca
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rerc
      deployment: rerc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rerc
        deployment: rerc
    spec:
      containers:
      - env:
        - name: authRealm
          value: SOUTHERNCOALITION
        - name: authResource
          value: southerncoalition
        - name: authSecret
          valueFrom:
            secretKeyRef:
              key: authSecret
              name: rerc-secret
        - name: authUrl
          valueFrom:
            secretKeyRef:
              key: authUrl
              name: rerc-secret
        - name: emailAuth
          valueFrom:
            secretKeyRef:
              key: emailAuth
              name: rerc-secret
        - name: emailFrom
          valueFrom:
            secretKeyRef:
              key: emailFrom
              name: rerc-secret
        - name: emailHost
          valueFrom:
            secretKeyRef:
              key: emailHost
              name: rerc-secret
        - name: emailPassword
          valueFrom:
            secretKeyRef:
              key: emailPassword
              name: rerc-secret
        - name: emailPort
          valueFrom:
            secretKeyRef:
              key: emailPort
              name: rerc-secret
        - name: emailSsl
          valueFrom:
            secretKeyRef:
              key: emailSsl
              name: rerc-secret
        - name: emailUsername
          valueFrom:
            secretKeyRef:
              key: emailUsername
              name: rerc-secret
        - name: jdbcHost
          valueFrom:
            secretKeyRef:
              key: host
              name: postgres-pguser-rerc
        - name: jdbcPort
          valueFrom:
            secretKeyRef:
              key: port
              name: postgres-pguser-rerc
        - name: jdbcDatabase
          valueFrom:
            secretKeyRef:
              key: dbname
              name: postgres-pguser-rerc
        - name: jdbcUsername
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-pguser-rerc
        - name: jdbcPassword
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-pguser-rerc
        - name: openshiftService
          value: rerc
#        - name: clusterPort
#          value: "8081"
#        - name: zookeeperHostName
#          value: zookeeper.rerc.svc
#        - name: zookeeperPort
#          value: "2181"
        - name: solrHostName
          value: default-solrcloud-common
        - name: solrPort
          value: "80"
        - name: solrUrl
          value: http://default-solrcloud-common.scsj-86c3ca.svc:80/solr/rerc
        - name: siteHostName
          value: rerc.southerncoalition.org
        - name: sitePort
          value: "8080"
        - name: siteBaseUrl
          value: https://rerc.southerncoalition.org
        - name: numberExecutors
          value: "5"
        - name: staticBaseUrl
          value: https://southerncoalition.neocities.org
        - name: siteZone
          value: America/New_York
        - name: JAVA_MAIN_CLASS
          value: org.southerncoalition.enus.vertx.AppVertx
        - name: ENABLE_DB_SOLR_SYNC
          value: "false"
        image: quay.io/computateorg/rerc:latest
        imagePullPolicy: Always
        name: rerc
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: cluster
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
            cpu: '1'
          requests:
            memory: 1Gi
            cpu: '1'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
