apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: scsj-86c3ca
spec:
  openshift: true
  backups:
    pgbackrest:
      # See https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/postgres/postgres.yaml
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      jobs:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
      sidecars:
        pgbackrestConfig:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        pgbackrest:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
      repoHost:
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 200Mi
            cpu: 200m
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 90Gi
                  memory: 200Mi
                  cpu: 200m
                limits:
                  memory: 200Mi
                  cpu: 200m
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 90Gi
            memory: 4Gi
            cpu: '2'
          limits:
            memory: 4Gi
            cpu: '2'
      replicas: 1
      name: 'postgres'
      resources:
        requests:
          memory: 200Mi
          cpu: 200m
        limits:
          memory: 200Mi
          cpu: 200m
  # See https://www.crunchydata.com/developers/download-postgres/containers/postgis
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.1-3.3-0
  postgresVersion: 15
  postGISVersion: 3.3.0
  users:
    - name: sso
      options: "SUPERUSER"
      databases:
        - sso
    - name: opendatapolicing
      options: "SUPERUSER"
      databases:
        - opendatapolicing
    - name: rerc
      options: "SUPERUSER"
      databases:
        - rerc
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host sso sso all md5"
          - "local sso sso trust"
          - "host opendatapolicing opendatapolicing all trust"
          - "local opendatapolicing opendatapolicing trust"
          - "host rerc rerc all trust"
          - "local rerc rerc trust"
