apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendatapolicing-persistent-volume-claim-ftp
  namespace: scsj-86c3ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
