kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: solr-operator-zookeeper-operator-pre-delete
  namespace: scsj-86c3ca
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - get
  - list
